stages:
  - build

build:
  tags:
    - docker
  image: fspr/lab:2019
  stage: build
  before_script:
    - source $CONDA_DIR/etc/profile.d/conda.sh
    - conda activate fspr
  script:
    - coverage run test.py
    - coverage html
  artifacts:
    expire_in: 1 week
    paths:
      - htmlcov

