stages:
  - build

build:
  tags:
    - docker
  image: fspr/lab:2019
  stage: build
  before_script:
    - source $CONDA_DIR/etc/profile.d/conda.sh
    - conda activate fspr
  script:
    - sphinx-build doc sphinx
    - sphinx-build -b doctest doc sphinx
    - coverage run test.py
    - coverage html
    - nosetests -sv --with-coverage --cover-package=. test.py
  artifacts:
    expire_in: 1 week
    paths:
      - htmlcov
      - sphinx
